### PR TITLE
Update README.md to add link to site https://gitehr.org

### PR DESCRIPTION
**Pull request by spdegabrielle**
add link to site https://gitehr.org

### CODE REVIEW

**Comment by pacharanero** [comment]
But if you are on gitehr.org why do you need a link to gitehr.org?

**Comment by spdegabrielle** [comment]
If you are on the GitHub org site https://github.com/gitehr or either repo, there is no link to the site. 

On second thoughts you can do it in the organisations settings and the repository details, but it is still nice to have a link in the readme

image

image

**Comment by pacharanero** [comment]
Ah sorry, brain not operational today! Good point, this is the README.md not that actual site viewable pages. Merging

**Comment by spdegabrielle** [comment]
No worries. I still think it is worth the organisations settings and the repository details as pictured above.

**Pull request merged**
